/* ADD BART closure info FOREIGN KEYS UP */
ALTER TABLE BARTDL
    ADD CONSTRAINT bartdl_ibfk_repoID FOREIGN KEY (repo) REFERENCES repo (repoID) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD CONSTRAINT bartdl_ibfk_evidenceType FOREIGN KEY (evidenceType) REFERENCES evidenceType (eviTypeID) ON UPDATE CASCADE ON DELETE SET NULL;